package entities;
// Generated Aug 14, 2012 11:11:34 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Admissionnotes generated by hbm2java
 */
public class Admissionnotes  implements java.io.Serializable {


     private Integer noteid;
     private int visitid;
     private String doctorsid;
     private String note;
     private Date date;

    public Admissionnotes() {
    }

	
    public Admissionnotes(int visitid, String note, Date date) {
        this.visitid = visitid;
        this.note = note;
        this.date = date;
    }
    public Admissionnotes(int visitid, String doctorsid, String note, Date date) {
       this.visitid = visitid;
       this.doctorsid = doctorsid;
       this.note = note;
       this.date = date;
    }
   
    public Integer getNoteid() {
        return this.noteid;
    }
    
    public void setNoteid(Integer noteid) {
        this.noteid = noteid;
    }
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    public String getDoctorsid() {
        return this.doctorsid;
    }
    
    public void setDoctorsid(String doctorsid) {
        this.doctorsid = doctorsid;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


