package entities;
// Generated Aug 14, 2012 11:11:34 AM by Hibernate Tools 3.2.1.GA



/**
 * Itemtype generated by hbm2java
 */
public class Itemtype  implements java.io.Serializable {


     private Integer id;
     private String itemType;

    public Itemtype() {
    }

    public Itemtype(String itemType) {
       this.itemType = itemType;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getItemType() {
        return this.itemType;
    }
    
    public void setItemType(String itemType) {
        this.itemType = itemType;
    }




}


