package entities;
// Generated Aug 14, 2012 11:11:34 AM by Hibernate Tools 3.2.1.GA



/**
 * Nhisinvestigation generated by hbm2java
 */
public class Nhisinvestigation  implements java.io.Serializable {


     private Integer code;
     private String investigation;
     private String gdrg;
     private String icd10;
     private double price;

    public Nhisinvestigation() {
    }

    public Nhisinvestigation(String investigation, String gdrg, String icd10, double price) {
       this.investigation = investigation;
       this.gdrg = gdrg;
       this.icd10 = icd10;
       this.price = price;
    }
   
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public String getInvestigation() {
        return this.investigation;
    }
    
    public void setInvestigation(String investigation) {
        this.investigation = investigation;
    }
    public String getGdrg() {
        return this.gdrg;
    }
    
    public void setGdrg(String gdrg) {
        this.gdrg = gdrg;
    }
    public String getIcd10() {
        return this.icd10;
    }
    
    public void setIcd10(String icd10) {
        this.icd10 = icd10;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }




}


