package entities;
// Generated Aug 13, 2012 3:00:10 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Patient generated by hbm2java
 */
public class Patient  implements java.io.Serializable {


     private String patientid;
     private String fname;
     private String lname;
     private String midname;
     private String gender;
     private String address;
     private String employer;
     private Date dateofbirth;
     private String contact;
     private String emergencyperson;
     private String emergencycontact;
     private String email;
     private Date dateofregistration;

    public Patient() {
    }

	
    public Patient(String patientid) {
        this.patientid = patientid;
    }
    public Patient(String patientid, String fname, String lname, String midname, String gender, String address, String employer, Date dateofbirth, String contact, String emergencyperson, String emergencycontact, String email, Date dateofregistration) {
       this.patientid = patientid;
       this.fname = fname;
       this.lname = lname;
       this.midname = midname;
       this.gender = gender;
       this.address = address;
       this.employer = employer;
       this.dateofbirth = dateofbirth;
       this.contact = contact;
       this.emergencyperson = emergencyperson;
       this.emergencycontact = emergencycontact;
       this.email = email;
       this.dateofregistration = dateofregistration;
    }
   
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getMidname() {
        return this.midname;
    }
    
    public void setMidname(String midname) {
        this.midname = midname;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmployer() {
        return this.employer;
    }
    
    public void setEmployer(String employer) {
        this.employer = employer;
    }
    public Date getDateofbirth() {
        return this.dateofbirth;
    }
    
    public void setDateofbirth(Date dateofbirth) {
        this.dateofbirth = dateofbirth;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getEmergencyperson() {
        return this.emergencyperson;
    }
    
    public void setEmergencyperson(String emergencyperson) {
        this.emergencyperson = emergencyperson;
    }
    public String getEmergencycontact() {
        return this.emergencycontact;
    }
    
    public void setEmergencycontact(String emergencycontact) {
        this.emergencycontact = emergencycontact;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getDateofregistration() {
        return this.dateofregistration;
    }
    
    public void setDateofregistration(Date dateofregistration) {
        this.dateofregistration = dateofregistration;
    }




}


