package entities;
// Generated Aug 13, 2012 3:00:10 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Patienttreatment generated by hbm2java
 */
public class Patienttreatment  implements java.io.Serializable {


     private Integer id;
     private String patientid;
     private String code;
     private int treatmentid;
     private String dosage;
     private int visitationid;
     private Date date;
     private double price;
     private Integer quantity;
     private String type;
     private String note;
     private String dispensed;

    public Patienttreatment() {
    }

	
    public Patienttreatment(String patientid, String code, int treatmentid, String dosage, int visitationid, Date date, double price, String dispensed) {
        this.patientid = patientid;
        this.code = code;
        this.treatmentid = treatmentid;
        this.dosage = dosage;
        this.visitationid = visitationid;
        this.date = date;
        this.price = price;
        this.dispensed = dispensed;
    }
    public Patienttreatment(String patientid, String code, int treatmentid, String dosage, int visitationid, Date date, double price, Integer quantity, String type, String note, String dispensed) {
       this.patientid = patientid;
       this.code = code;
       this.treatmentid = treatmentid;
       this.dosage = dosage;
       this.visitationid = visitationid;
       this.date = date;
       this.price = price;
       this.quantity = quantity;
       this.type = type;
       this.note = note;
       this.dispensed = dispensed;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public int getTreatmentid() {
        return this.treatmentid;
    }
    
    public void setTreatmentid(int treatmentid) {
        this.treatmentid = treatmentid;
    }
    public String getDosage() {
        return this.dosage;
    }
    
    public void setDosage(String dosage) {
        this.dosage = dosage;
    }
    public int getVisitationid() {
        return this.visitationid;
    }
    
    public void setVisitationid(int visitationid) {
        this.visitationid = visitationid;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getDispensed() {
        return this.dispensed;
    }
    
    public void setDispensed(String dispensed) {
        this.dispensed = dispensed;
    }




}


