package entities;
// Generated Aug 13, 2012 3:00:10 PM by Hibernate Tools 3.2.1.GA



/**
 * Wardnote generated by hbm2java
 */
public class Wardnote  implements java.io.Serializable {


     private Integer noteid;
     private int wardid;
     private String nurseid;
     private String note;

    public Wardnote() {
    }

	
    public Wardnote(int wardid, String note) {
        this.wardid = wardid;
        this.note = note;
    }
    public Wardnote(int wardid, String nurseid, String note) {
       this.wardid = wardid;
       this.nurseid = nurseid;
       this.note = note;
    }
   
    public Integer getNoteid() {
        return this.noteid;
    }
    
    public void setNoteid(Integer noteid) {
        this.noteid = noteid;
    }
    public int getWardid() {
        return this.wardid;
    }
    
    public void setWardid(int wardid) {
        this.wardid = wardid;
    }
    public String getNurseid() {
        return this.nurseid;
    }
    
    public void setNurseid(String nurseid) {
        this.nurseid = nurseid;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


