package entities;
// Generated Aug 14, 2012 11:11:34 AM by Hibernate Tools 3.2.1.GA



/**
 * Ward generated by hbm2java
 */
public class Ward  implements java.io.Serializable {


     private Integer wardid;
     private String wardname;
     private int numberofbeds;
     private int occupied;

    public Ward() {
    }

    public Ward(String wardname, int numberofbeds, int occupied) {
       this.wardname = wardname;
       this.numberofbeds = numberofbeds;
       this.occupied = occupied;
    }
   
    public Integer getWardid() {
        return this.wardid;
    }
    
    public void setWardid(Integer wardid) {
        this.wardid = wardid;
    }
    public String getWardname() {
        return this.wardname;
    }
    
    public void setWardname(String wardname) {
        this.wardname = wardname;
    }
    public int getNumberofbeds() {
        return this.numberofbeds;
    }
    
    public void setNumberofbeds(int numberofbeds) {
        this.numberofbeds = numberofbeds;
    }
    public int getOccupied() {
        return this.occupied;
    }
    
    public void setOccupied(int occupied) {
        this.occupied = occupied;
    }




}


