package entities;
// Generated Sep 4, 2012 2:01:55 PM by Hibernate Tools 3.2.1.GA



/**
 * Diagnosis generated by hbm2java
 */
public class Diagnosis  implements java.io.Serializable {


     private Integer id;
     private String diagnosisCode;
     private String diagnosis;

    public Diagnosis() {
    }

    public Diagnosis(String diagnosisCode, String diagnosis) {
       this.diagnosisCode = diagnosisCode;
       this.diagnosis = diagnosis;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDiagnosisCode() {
        return this.diagnosisCode;
    }
    
    public void setDiagnosisCode(String diagnosisCode) {
        this.diagnosisCode = diagnosisCode;
    }
    public String getDiagnosis() {
        return this.diagnosis;
    }
    
    public void setDiagnosis(String diagnosis) {
        this.diagnosis = diagnosis;
    }




}


