package entities;
// Generated Sep 4, 2012 2:01:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Laborders generated by hbm2java
 */
public class Laborders  implements java.io.Serializable {


     private Integer orderid;
     private int visitid;
     private String fromdoc;
     private String todoc;
     private Date orderdate;
     private Date donedate;

    public Laborders() {
    }

	
    public Laborders(int visitid, String fromdoc, Date orderdate) {
        this.visitid = visitid;
        this.fromdoc = fromdoc;
        this.orderdate = orderdate;
    }
    public Laborders(int visitid, String fromdoc, String todoc, Date orderdate, Date donedate) {
       this.visitid = visitid;
       this.fromdoc = fromdoc;
       this.todoc = todoc;
       this.orderdate = orderdate;
       this.donedate = donedate;
    }
   
    public Integer getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }
    public int getVisitid() {
        return this.visitid;
    }
    
    public void setVisitid(int visitid) {
        this.visitid = visitid;
    }
    public String getFromdoc() {
        return this.fromdoc;
    }
    
    public void setFromdoc(String fromdoc) {
        this.fromdoc = fromdoc;
    }
    public String getTodoc() {
        return this.todoc;
    }
    
    public void setTodoc(String todoc) {
        this.todoc = todoc;
    }
    public Date getOrderdate() {
        return this.orderdate;
    }
    
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }
    public Date getDonedate() {
        return this.donedate;
    }
    
    public void setDonedate(Date donedate) {
        this.donedate = donedate;
    }




}


