package entities;
// Generated Sep 4, 2012 2:01:55 PM by Hibernate Tools 3.2.1.GA



/**
 * Nhistreatment generated by hbm2java
 */
public class Nhistreatment  implements java.io.Serializable {


     private Integer code;
     private String drug;
     private double price;
     private String gdrg;
     private String icd10;

    public Nhistreatment() {
    }

    public Nhistreatment(String drug, double price, String gdrg, String icd10) {
       this.drug = drug;
       this.price = price;
       this.gdrg = gdrg;
       this.icd10 = icd10;
    }
   
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public String getDrug() {
        return this.drug;
    }
    
    public void setDrug(String drug) {
        this.drug = drug;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public String getGdrg() {
        return this.gdrg;
    }
    
    public void setGdrg(String gdrg) {
        this.gdrg = gdrg;
    }
    public String getIcd10() {
        return this.icd10;
    }
    
    public void setIcd10(String icd10) {
        this.icd10 = icd10;
    }




}


