package entities;
// Generated Sep 4, 2012 2:01:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Patient generated by hbm2java
 */
public class Patient  implements java.io.Serializable {


     private String patientid;
     private String fname;
     private String lname;
     private String midname;
     private String gender;
     private String address;
     private String employer;
     private Date dateofbirth;
     private String contact;
     private String emergencyperson;
     private String emergencycontact;
     private String email;
     private Date dateofregistration;
     private String country;
     private String city;
     private String maritalstatus;
     private String imglocation;

    public Patient() {
    }

	
    public Patient(String patientid) {
        this.patientid = patientid;
    }
    public Patient(String patientid, String fname, String lname, String midname, String gender, String address, String employer, Date dateofbirth, String contact, String emergencyperson, String emergencycontact, String email, Date dateofregistration, String country, String city, String maritalstatus, String imglocation) {
       this.patientid = patientid;
       this.fname = fname;
       this.lname = lname;
       this.midname = midname;
       this.gender = gender;
       this.address = address;
       this.employer = employer;
       this.dateofbirth = dateofbirth;
       this.contact = contact;
       this.emergencyperson = emergencyperson;
       this.emergencycontact = emergencycontact;
       this.email = email;
       this.dateofregistration = dateofregistration;
       this.country = country;
       this.city = city;
       this.maritalstatus = maritalstatus;
       this.imglocation = imglocation;
    }
   
    public String getPatientid() {
        return this.patientid;
    }
    
    public void setPatientid(String patientid) {
        this.patientid = patientid;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getMidname() {
        return this.midname;
    }
    
    public void setMidname(String midname) {
        this.midname = midname;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmployer() {
        return this.employer;
    }
    
    public void setEmployer(String employer) {
        this.employer = employer;
    }
    public Date getDateofbirth() {
        return this.dateofbirth;
    }
    
    public void setDateofbirth(Date dateofbirth) {
        this.dateofbirth = dateofbirth;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getEmergencyperson() {
        return this.emergencyperson;
    }
    
    public void setEmergencyperson(String emergencyperson) {
        this.emergencyperson = emergencyperson;
    }
    public String getEmergencycontact() {
        return this.emergencycontact;
    }
    
    public void setEmergencycontact(String emergencycontact) {
        this.emergencycontact = emergencycontact;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getDateofregistration() {
        return this.dateofregistration;
    }
    
    public void setDateofregistration(Date dateofregistration) {
        this.dateofregistration = dateofregistration;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getMaritalstatus() {
        return this.maritalstatus;
    }
    
    public void setMaritalstatus(String maritalstatus) {
        this.maritalstatus = maritalstatus;
    }
    public String getImglocation() {
        return this.imglocation;
    }
    
    public void setImglocation(String imglocation) {
        this.imglocation = imglocation;
    }




}


