package entities;
// Generated Sep 4, 2012 2:01:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Qualification generated by hbm2java
 */
public class Qualification  implements java.io.Serializable {


     private Integer quid;
     private String qualification;
     private Date from;
     private Date to;
     private String institution;
     private String staffid;

    public Qualification() {
    }

    public Qualification(String qualification, Date from, Date to, String institution, String staffid) {
       this.qualification = qualification;
       this.from = from;
       this.to = to;
       this.institution = institution;
       this.staffid = staffid;
    }
   
    public Integer getQuid() {
        return this.quid;
    }
    
    public void setQuid(Integer quid) {
        this.quid = quid;
    }
    public String getQualification() {
        return this.qualification;
    }
    
    public void setQualification(String qualification) {
        this.qualification = qualification;
    }
    public Date getFrom() {
        return this.from;
    }
    
    public void setFrom(Date from) {
        this.from = from;
    }
    public Date getTo() {
        return this.to;
    }
    
    public void setTo(Date to) {
        this.to = to;
    }
    public String getInstitution() {
        return this.institution;
    }
    
    public void setInstitution(String institution) {
        this.institution = institution;
    }
    public String getStaffid() {
        return this.staffid;
    }
    
    public void setStaffid(String staffid) {
        this.staffid = staffid;
    }




}


