package entities;
// Generated Sep 4, 2012 2:01:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Stafftable generated by hbm2java
 */
public class Stafftable  implements java.io.Serializable {


     private String staffid;
     private String firstname;
     private String lastname;
     private String othername;
     private String ssn;
     private Date dob;
     private String placeofbirth;
     private Date yearofemployment;
     private int role;
     private String extraduty;
     private String address;
     private String contact;
     private String nextofkin;
     private String nextofkincontact;
     private int unit;
     private String imglocation;

    public Stafftable() {
    }

	
    public Stafftable(String staffid, String firstname, String lastname, Date dob, String placeofbirth, Date yearofemployment, int role, String contact, String nextofkin, int unit) {
        this.staffid = staffid;
        this.firstname = firstname;
        this.lastname = lastname;
        this.dob = dob;
        this.placeofbirth = placeofbirth;
        this.yearofemployment = yearofemployment;
        this.role = role;
        this.contact = contact;
        this.nextofkin = nextofkin;
        this.unit = unit;
    }
    public Stafftable(String staffid, String firstname, String lastname, String othername, String ssn, Date dob, String placeofbirth, Date yearofemployment, int role, String extraduty, String address, String contact, String nextofkin, String nextofkincontact, int unit, String imglocation) {
       this.staffid = staffid;
       this.firstname = firstname;
       this.lastname = lastname;
       this.othername = othername;
       this.ssn = ssn;
       this.dob = dob;
       this.placeofbirth = placeofbirth;
       this.yearofemployment = yearofemployment;
       this.role = role;
       this.extraduty = extraduty;
       this.address = address;
       this.contact = contact;
       this.nextofkin = nextofkin;
       this.nextofkincontact = nextofkincontact;
       this.unit = unit;
       this.imglocation = imglocation;
    }
   
    public String getStaffid() {
        return this.staffid;
    }
    
    public void setStaffid(String staffid) {
        this.staffid = staffid;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getOthername() {
        return this.othername;
    }
    
    public void setOthername(String othername) {
        this.othername = othername;
    }
    public String getSsn() {
        return this.ssn;
    }
    
    public void setSsn(String ssn) {
        this.ssn = ssn;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getPlaceofbirth() {
        return this.placeofbirth;
    }
    
    public void setPlaceofbirth(String placeofbirth) {
        this.placeofbirth = placeofbirth;
    }
    public Date getYearofemployment() {
        return this.yearofemployment;
    }
    
    public void setYearofemployment(Date yearofemployment) {
        this.yearofemployment = yearofemployment;
    }
    public int getRole() {
        return this.role;
    }
    
    public void setRole(int role) {
        this.role = role;
    }
    public String getExtraduty() {
        return this.extraduty;
    }
    
    public void setExtraduty(String extraduty) {
        this.extraduty = extraduty;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getNextofkin() {
        return this.nextofkin;
    }
    
    public void setNextofkin(String nextofkin) {
        this.nextofkin = nextofkin;
    }
    public String getNextofkincontact() {
        return this.nextofkincontact;
    }
    
    public void setNextofkincontact(String nextofkincontact) {
        this.nextofkincontact = nextofkincontact;
    }
    public int getUnit() {
        return this.unit;
    }
    
    public void setUnit(int unit) {
        this.unit = unit;
    }
    public String getImglocation() {
        return this.imglocation;
    }
    
    public void setImglocation(String imglocation) {
        this.imglocation = imglocation;
    }




}


