package entities;
// Generated Sep 4, 2012 2:01:55 PM by Hibernate Tools 3.2.1.GA



/**
 * Symptoms generated by hbm2java
 */
public class Symptoms  implements java.io.Serializable {


     private Integer symptomid;
     private String symptomname;

    public Symptoms() {
    }

    public Symptoms(String symptomname) {
       this.symptomname = symptomname;
    }
   
    public Integer getSymptomid() {
        return this.symptomid;
    }
    
    public void setSymptomid(Integer symptomid) {
        this.symptomid = symptomid;
    }
    public String getSymptomname() {
        return this.symptomname;
    }
    
    public void setSymptomname(String symptomname) {
        this.symptomname = symptomname;
    }




}


